### ISSUE TITLE
Handle python-valve tasks in an async manner

### ISSUE THREAD

**Issue by GoodGuyGroves** [rsatf/Miss_Pauling#8]
Do server checks in an async manner.

Here are 3 examples of when we use python-valve to interact with the TF2 servers. All of these tasks are blocking the main event loop.
https://github.com/rsatf/Miss_Pauling/blob/master/cogs/pug.py#L59
https://github.com/rsatf/Miss_Pauling/blob/master/cogs/pug.py#L366
https://github.com/rsatf/Miss_Pauling/blob/master/cogs/servers.py#L67

**Comment by kevelbreh** [comment]
It's safe to say that this is no longer relevant? I found no python-valve references anywhere
